CREATE TABLE public.users (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	age int4 NOT NULL,
	created_at timestamp(6) NULL,
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

INSERT INTO users ("age", "email", "name") VALUES ('30', 'test@mail.com', 'testUser');